export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'

export const NOTIFICAR_USUARIO = 'NOTIFICAR_USUARIO'
export const EXCLUIR_NOTIFICACAO = 'EXCLUIR_NOTIFICACAO'